### ISSUE TITLE
Feature Request: run spotify-tray again to show the window

### ISSUE THREAD

**Issue by A1ca7raz** [macdems/yet-another-spotify-tray#4]
I used to click the close button to hide Spotify in the tray on Windows and click Spotify pinned in my dock to show up Spotify.
On Linux, when spotify tray is running, run spotify-tray will show it is already running, run spotify will show up a broken Spotify window (won't break the spotify already running).
I wonder can you add a feature that when a running spotify-tray detected, try to show the window instead of starting a new Spotify.

**Comment by macdems** [comment]
This is very good idea. Unfortunately, I cannot implement desired behavior, when someone launches plain Spotify, however, now launching `spotify-tray` again shows the window.
